### ISSUE TITLE
Error when run knex.schema.createTable with primary()

### ISSUE THREAD

**Issue by eneias-emir** [Tomas2D/knex-firebird-dialect#24]
Missing parameter in file lib\schema\tablecompiler.js on line 57:

original:

value: function primary() {

changed:

value: function primary(columns) {

On line 59 this function need columns parameter.

When create a table with .primary() in a id column, this result in an error due missing coluns parameter

**Comment by Tomas2D** [comment]
Fixed at version 1.3.0., thanks for reporting an issue.
