### ISSUE TITLE
Querying some char(1) columns returns a wrong value

### ISSUE THREAD

**Issue by mariocarro** [Tomas2D/knex-firebird-dialect#245]
Some queries on char(1) columns return return strings with 4 characters (with 3 added spaces on the right).

**Comment by Tomas2D** [comment]
I can reproduce the issue. However, the bug is inside the underlying package `node-firebird` - this bug has already been reported: https://github.com/hgourvest/node-firebird/issues/84. I can't do anything about it right now.

In the future, I would like to switch to https://github.com/asfernandes/node-firebird-drivers, but firstly, https://github.com/asfernandes/node-firebird-drivers/issues/138 needs to get resolved.

**Comment by Tomas2D** [comment]
You can now play with `knex-firebird-dialect@2.0.0-alpha.4`; I am currently testing it. Once stable, I will release it.

**Comment by mariocarro** [comment]
I upgraded to that version. After running the software again at first it didn't find libfbclient.so, but that was easy to solve with a symlink. After fixing that, the connection to the database fails because it looks for /DATABASE which does not exist. The database name it specified is DATABASE (without the '/').

**Comment by Tomas2D** [comment]
Interesting. Maybe checkout the tests in this repository. I am curring running this on macOS and also on the Linux server.

**Comment by mariocarro** [comment]
Perhaps the problem is that I use firebird aliases, instead of the physical database path?

**Comment by Tomas2D** [comment]
This is possible. I would recommend you to try the following example:
https://github.com/asfernandes/node-firebird-drivers/blob/master/packages/node-firebird-driver-native/README.md

Just do slight modifications to try it with firebird aliases.

**Comment by Tomas2D** [comment]
Were you able to make it work? @mariocarro

**Comment by mariocarro** [comment]
I apologize for the delay! Yes, changing the database alias to its path allows the connection to continue and then the char(1) columns return the correct values. Everything I've tried so far seems to work well. The remaining details (failure to find libfbclient and alias support) depend, I suppose, on node-firebird-driver-native, so this issue is resolved as far as I'm concerned. Thank you!
