### ISSUE TITLE
Error when try run "knex migrate:latest"

### ISSUE THREAD

**Issue by renato-saldanha** [Tomas2D/knex-firebird-dialect#5]
I'm trying create database in node, but receive this error message:

![Screenshot_2](https://user-images.githubusercontent.com/19418483/161055001-d943db13-e34f-43d0-a160-339c80afc767.jpg)

**Comment by Tomas2D** [comment]
Hello, this issue is mentioned in the README.
Use `const knexFirebirdDialect = require("knex-firebird-dialect").default` for import.

**Comment by renato-saldanha** [comment]
when use default i get this:

![Screenshot_3](https://user-images.githubusercontent.com/19418483/161062908-04c4d1a7-79ea-444c-b8f7-e61277fa4f25.jpg)

**Comment by renato-saldanha** [comment]
cant create an column named with INDEX

**Comment by renato-saldanha** [comment]
I created the table manually using quotes in the INDEX column, but when executing "knex migrate:latest" it reports the following error even running "knex migrate:unlock" command:


![Screenshot_4](https://user-images.githubusercontent.com/19418483/161081559-912aa238-5795-44b1-8f10-3980146592ef.jpg)

**Comment by Tomas2D** [comment]
Library is not tested for migrations yet as it was not needed on the project I was working for. I will take a look at it in a spare time.

**Comment by Tomas2D** [comment]
The first error (when creating `knex_migrations_lock` table occurs due to the fact that `index` is a reserved keyword in Firebird database. 

To demonstrate this you can run 
```js
await knex.schema.createTable("knex_migrations_lock", function (table) {
      table.increments("index");
      table.integer("is_locked");
});
```

but 

```js
await knex.schema.createTable("knex_migrations_lock", function (table) {
      table.increments("id");
      table.integer("is_locked");
});
```

will work.

**Comment by renato-saldanha** [comment]
After commenting the line 358 in Migrator.js i can generate tables, but i couldn't find the line that create the "table migration lock" to alter INDEX column nomenclature

**Comment by Tomas2D** [comment]
Maybe using some kind on our side could possible allow to use `index` as proper column name.
